"""Wizard models for the Guided Grant Application Wizard.

Pydantic models for wizard sessions that walk users through grant
applications via AI-powered interviews. Supports two entry paths:
- have_grant: User already has a specific grant opportunity
- find_grant: User wants to discover matching grants

The wizard collects grant context, conducts an AI interview, and
produces a structured plan (staffing, budget, timeline, metrics).
"""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Grant Context sub-models
# ---------------------------------------------------------------------------


class GrantRequirement(BaseModel):
    """A single requirement extracted from a grant opportunity."""

    category: Literal[
        "narrative",
        "budget",
        "timeline",
        "evaluation",
        "organizational",
        "staffing",
        "other",
    ] = Field(..., description="Requirement category")
    description: str = Field(..., description="Description of the requirement")
    is_mandatory: bool = Field(
        default=True, description="Whether this requirement is mandatory"
    )


class KeyDate(BaseModel):
    """A key date associated with a grant opportunity."""

    date: Optional[str] = Field(
        None, description="Date string (ISO 8601 or human-readable)"
    )
    description: str = Field(..., description="What this date represents")


class GrantContext(BaseModel):
    """Parsed grant opportunity context collected during the wizard."""

    grant_name: Optional[str] = Field(None, description="Name of the grant program")
    grantor: Optional[str] = Field(None, description="Granting organization")
    cfda_number: Optional[str] = Field(
        None, description="CFDA/Assistance Listing number"
    )
    deadline: Optional[str] = Field(None, description="Application deadline")
    funding_amount_min: Optional[float] = Field(
        None, description="Minimum funding amount"
    )
    funding_amount_max: Optional[float] = Field(
        None, description="Maximum funding amount"
    )
    grant_type: Optional[
        Literal["federal", "state", "foundation", "corporate", "other"]
    ] = Field(None, description="Type of grant")
    eligibility_text: Optional[str] = Field(
        None, description="Raw eligibility criteria text"
    )
    match_requirement: Optional[str] = Field(
        None, description="Match/cost-share requirement description"
    )
    requirements: List[GrantRequirement] = Field(
        default_factory=list, description="Parsed grant requirements"
    )
    key_dates: List[KeyDate] = Field(
        default_factory=list, description="Important dates and deadlines"
    )
    evaluation_criteria: Optional[str] = Field(
        None, description="How applications will be evaluated"
    )
    contact_info: Optional[str] = Field(
        None, description="Grant program contact information"
    )
    summary: Optional[str] = Field(
        None, description="AI-generated summary of the grant opportunity"
    )


# ---------------------------------------------------------------------------
# Plan Data sub-models
# ---------------------------------------------------------------------------


class StaffingEntry(BaseModel):
    """A staffing plan entry for a grant application."""

    role: str = Field(..., description="Position/role title")
    fte: float = Field(..., description="Full-time equivalent allocation")
    salary_estimate: float = Field(..., description="Estimated salary/cost")
    responsibilities: str = Field(..., description="Key responsibilities for this role")


class BudgetEntry(BaseModel):
    """A budget line item for a grant application."""

    category: str = Field(
        ..., description="Budget category (personnel, equipment, etc.)"
    )
    amount: float = Field(..., description="Dollar amount")
    justification: str = Field(..., description="Justification for this expense")


class TimelinePhase(BaseModel):
    """A phase in the project timeline."""

    phase: str = Field(..., description="Phase name")
    start: str = Field(..., description="Phase start date")
    end: str = Field(..., description="Phase end date")
    milestones: List[str] = Field(
        default_factory=list, description="Key milestones in this phase"
    )


class MetricEntry(BaseModel):
    """A performance metric for evaluation."""

    metric: str = Field(..., description="Metric name")
    target: str = Field(..., description="Target value or outcome")
    measurement_method: str = Field(..., description="How this metric will be measured")


class PlanData(BaseModel):
    """Structured plan data generated by the wizard."""

    program_overview: Optional[str] = Field(
        None, description="High-level program description"
    )
    staffing_plan: List[StaffingEntry] = Field(
        default_factory=list, description="Staffing plan entries"
    )
    budget: List[BudgetEntry] = Field(
        default_factory=list, description="Budget line items"
    )
    timeline: List[TimelinePhase] = Field(
        default_factory=list, description="Project timeline phases"
    )
    deliverables: List[str] = Field(
        default_factory=list, description="Expected deliverables"
    )
    metrics: List[MetricEntry] = Field(
        default_factory=list, description="Performance metrics"
    )
    partnerships: List[str] = Field(
        default_factory=list, description="Partner organizations"
    )


# ---------------------------------------------------------------------------
# Wizard Session CRUD models
# ---------------------------------------------------------------------------


class WizardSessionCreate(BaseModel):
    """Request model for creating a new wizard session."""

    entry_path: Literal["have_grant", "find_grant"] = Field(
        ..., description="How the user is entering the wizard"
    )


class WizardSessionUpdate(BaseModel):
    """Request model for updating an existing wizard session."""

    current_step: Optional[int] = Field(None, description="Current wizard step index")
    status: Optional[Literal["in_progress", "completed", "abandoned"]] = Field(
        None, description="Session status"
    )
    grant_context: Optional[GrantContext] = Field(
        None, description="Updated grant context data"
    )
    interview_data: Optional[Dict[str, Any]] = Field(
        None, description="Updated interview Q&A data"
    )
    plan_data: Optional[PlanData] = Field(None, description="Updated plan data")


class WizardSession(BaseModel):
    """Full wizard session record returned from the API."""

    id: str
    user_id: str
    conversation_id: Optional[str] = None
    proposal_id: Optional[str] = None
    card_id: Optional[str] = None
    entry_path: str
    current_step: int = 0
    status: str = "in_progress"
    grant_context: Optional[GrantContext] = Field(default_factory=GrantContext)
    interview_data: Dict[str, Any] = Field(default_factory=dict)
    plan_data: Optional[PlanData] = Field(default_factory=PlanData)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Specialized response models
# ---------------------------------------------------------------------------


class ProcessGrantResponse(BaseModel):
    """Response from processing a grant document/URL."""

    grant_context: GrantContext = Field(
        ..., description="Parsed grant context from the document"
    )
    card_id: Optional[str] = Field(
        None, description="Card ID if a matching card was found or created"
    )
