#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Enhanced Discovery Queue UX

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Enhanced Discovery Queue UX"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo -e "${YELLOW}Starting Frontend Dev Server...${NC}"

# Frontend
cd frontend/foresight-frontend
pnpm install --prefer-offline &
wait

echo "Starting Vite dev server..."
pnpm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 5173 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:5173"
echo "  Discovery Queue: http://localhost:5173/discovery"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $FRONTEND_PID
